module.exports = {
    active: 'Trạng thái',
    category_id: 'Mã thể loại',
    category: 'Thể loại',
    comment_amout: 'Số bình luận',
    createdAt: 'Ngày tạo',
    description: 'Mô tả',
    discount_pd: 'Giảm giá sản phẩm',
    id: 'id',
    image_id: 'Mã ảnh',
    image: 'Ảnh',
    inventory: 'Tồn kho',
    name: 'Tên',
    price: 'Giá',
    sold: 'Đã bán',
    updatedAt: 'Ngày cập nhập',
    vote: 'Đánh giá',
}